config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.authtoken.views import obtain_auth_token

from modules.views import IndexView

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Educational Modules",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(template_name='modules/index.html'), name='index'),
    path('modules/', include('modules.urls', namespace='modules')),
    path('users/', include('users.urls', namespace='users')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

modules/urls.py
from django.urls import path

from modules.views import ModuleCreateAPIView, ModuleListAPIView, ModuleDetailAPIView, ModuleDestroyAPIView, \
    ModuleUpdateAPIView, SubscriptionView, SubscriptionListAPIView, LessonCreateAPIView, \
    LessonListAPIView, LessonDetailAPIView, LessonDestroyAPIView, LessonUpdateAPIView

app_name = 'modules'

urlpatterns = [
    # Модули
    path('create/', ModuleCreateAPIView.as_view(), name='module_create'),
    path('list/', ModuleListAPIView.as_view(), name='module_list'),
    path('detail/<int:pk>/', ModuleDetailAPIView.as_view(), name='module_detail'),
    path('delete/<int:pk>/', ModuleDestroyAPIView.as_view(), name='module_delete'),
    path('update/<int:pk>/', ModuleUpdateAPIView.as_view(), name='module_update'),
    # Уроки
    path('lessons/create/', LessonCreateAPIView.as_view(), name='lesson_create'),
    path('lessons/list/', LessonListAPIView.as_view(), name='lesson_list'),
    path('lessons/detail/<int:pk>/', LessonDetailAPIView.as_view(), name='lesson_detail'),
    path('lessons/delete/<int:pk>/', LessonDestroyAPIView.as_view(), name='lesson_delete'),
    path('lessons/update/<int:pk>/', LessonUpdateAPIView.as_view(), name='lesson_update'),
    # Подписка
    path('subscription/<int:pk>/', SubscriptionView.as_view(), name='module_subscription'),
    path('subscription/list/', SubscriptionListAPIView.as_view(), name='module_subscription_list'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from users.views import UserRegisterView, UserListView, UserLoginView, UserProfileView, UserProfileUpdateView, \
    UserDeleteView, UserPasswordResetConfirmView, UserPasswordResetView, confirm_registration, UserRegisterAPIView

from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'users'

urlpatterns = [
    path('api/register/', UserRegisterAPIView.as_view(), name='api_register'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='profile_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'), # сброс пароля пользователя
    path('password_reset_confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'), # подтверждение сброса пароля пользователя
    path('confirm/<str:token>/', confirm_registration, name='confirmation_link'), # путь ссылки на подтверждение регистрации, которая отправляется пользователю по email
    path('confirm-registration/<uuid:token>/', confirm_registration, name='confirm_registration'), # путь запроса, когда пользователь переходит по ссылке для подтверждения регистрации

# token
    path(
        "users/login/",
        TokenObtainPairView.as_view(permission_classes=(AllowAny,)),
        name="login",
    ),
    path(
        "users/token/refresh/",
        TokenRefreshView.as_view(permission_classes=(AllowAny,)),
        name="token_refresh",
    ),

]

modules/models.py
from django.db import models
NULLABLE = {
    'null': True,
    'blank': True,
}


class Module(models.Model):
    """Образовательный Модуль"""
    serial_number = models.AutoField(primary_key=True, verbose_name="Порядковый номер")
    title = models.CharField(max_length=150, verbose_name='Название модуля', help_text="Введите название модуля")
    description = models.TextField(verbose_name='Описание', help_text="Опишите основные материалы модуля")
    preview = models.ImageField(upload_to="modules/previews", verbose_name="Превью", **NULLABLE, help_text="Загрузите превью")
    owner = models.ForeignKey('users.User', on_delete=models.SET_NULL, verbose_name="Владелец модуля", **NULLABLE)

    last_update = models.DateField(auto_now=True, verbose_name='Последнее обновление')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Образовательный модуль'
        verbose_name_plural = 'Образовательные модули'
        ordering = ('serial_number',)

class Lesson(models.Model):
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name='Курс', related_name='lessons')
    title = models.CharField(max_length=150, verbose_name='Название урока', help_text='Введите название урока')
    description = models.TextField(verbose_name='Описание урока', help_text='Опишите основные материалы урока')
    preview = models.ImageField(upload_to='modules/lessons/previews', verbose_name='Превью урока', **NULLABLE, help_text='Загрузите превью урока')
    video_link = models.URLField(verbose_name='Ссылка на видео', **NULLABLE, help_text='Укажите ссылку на видео урока')
    owner = models.ForeignKey('users.User',on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец урока')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')


    class Meta:
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'

class Subscription(models.Model):
    """Подписка на Модуль"""
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Пользователь')
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name='модуль')

    def __str__(self):
        return f'{self.user} - {self.module}'

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('pk',)
        unique_together = ('user', 'module')

modules/views.py
from django.views.generic import TemplateView
from rest_framework import status
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView, DestroyAPIView, UpdateAPIView, \
    get_object_or_404, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from modules.models import Module, Subscription, Lesson
from modules.paginators import ModulePagination
from modules.permissions import IsOwnerOrAdmin
from modules.serializers import ModuleSerializer, SubscriptionSerializer, LessonSerializer
from rest_framework.response import Response


class IndexView(TemplateView):
    """Контроллер просмотра домашней страницы"""
    template_name = 'modules/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['modules'] = Module.objects.all()  # Получаем все модули
        return context

class ModuleCreateAPIView(CreateAPIView):
    """ Создание модуля """
    serializer_class = ModuleSerializer
    permission_classes = [IsOwnerOrAdmin]

    def perform_create(self, serializer):
        # Устанавливаем владельца модуля как текущего пользователя
        serializer.save(owner=self.request.user)


class ModuleListAPIView(ListAPIView):
    """ Контроллер просмотра списка модулей """
    serializer_class = ModuleSerializer
    queryset = Module.objects.all()
    pagination_class = ModulePagination


class ModuleDetailAPIView(RetrieveAPIView):
    """ Подробная информация о модуле """
    serializer_class = ModuleSerializer
    queryset = Module.objects.all()
    permission_classes = [IsAuthenticated]

class ModuleDestroyAPIView(DestroyAPIView):
    """ Удаление модуля """
    serializer_class = ModuleSerializer
    queryset = Module.objects.all()
    permission_classes = [IsOwnerOrAdmin]


class ModuleUpdateAPIView(UpdateAPIView):
    """ Редактирование модуля """
    serializer_class = ModuleSerializer
    queryset = Module.objects.all()
    permission_classes = [IsOwnerOrAdmin]

    def perform_update(self, serializer):
        """ Обновление модуля """
        serializer.save()

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)

class LessonCreateAPIView(CreateAPIView):
    """Создание урока"""
    serializer_class = LessonSerializer
    permission_classes = [IsOwnerOrAdmin]

    def perform_create(self, serializer):
        # Устанавливаем владельца модуля как текущего пользователя
        serializer.save(owner=self.request.user)


class LessonListAPIView(ListAPIView):
    """Список уроков"""
    serializer_class = LessonSerializer
    queryset = Lesson.objects.all()


class LessonDetailAPIView(RetrieveAPIView):
    """Подробная информация об уроке"""
    serializer_class = LessonSerializer
    queryset = Lesson.objects.all()
    permission_classes = [IsAuthenticated]

    def get_object(self):
        """Подсчет просмотров"""
        data = super().get_object()
        data.views_count += 1
        data.save()
        return data


class LessonDestroyAPIView(DestroyAPIView):
    """Удаление урока"""
    serializer_class = LessonSerializer
    queryset = Lesson.objects.all()
    permission_classes = [IsOwnerOrAdmin]

class LessonUpdateAPIView(RetrieveUpdateAPIView):
    """Редактирование урока"""
    serializer_class = LessonSerializer
    queryset = Lesson.objects.all()
    permission_classes = [IsOwnerOrAdmin]

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)

class SubscriptionView(APIView):
    """ Подписка на модуль """
    def post(self, request, pk, *args, **kwargs):
        user = request.user
        module = get_object_or_404(Module, pk=pk)

        if module:
            subscription, created = Subscription.objects.get_or_create(user=user, module=module)
            if created:
                message = 'Подписка оформлена'
            else:
                subscription.delete()
                message = 'Подписка отменена'
            return Response({'message': message}, status=status.HTTP_200_OK)
        else:
            return Response({'error': 'Модуль не найден'}, status=status.HTTP_404_NOT_FOUND)

class SubscriptionListAPIView(ListAPIView):
    """ Список подписок для текущего пользователя """
    serializer_class = SubscriptionSerializer
    permission_classes = [IsAuthenticated]  # Убедитесь, что пользователь аутентифицирован

    def get_queryset(self):
        user = self.request.user
        return Subscription.objects.filter(user=user)  # Возвращаем подписки только для текущего пользователя

modules/templates/modules/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Образовательный сервис для обучения">
    <title>{% block title %}Educational modules{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Образовательный сервис для обучения U-Kids</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:user_profile' %}">Профиль</a>
                        </li>
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:user_delete' user.pk %}">Удалить профиль</a>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="nav-link btn btn-link">Выйти</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container my-5">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

modules/templates/modules/index.html
{% extends "modules/base.html" %}{% block title %}Главная{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Все Модули</h1>
            <ul class="list-unstyled">
                {% for module in modules %}
                <li class="d-flex justify-content-between align-items-center">
                    <strong>{{ module.title }}</strong>
                    <div class="btn-group">
                        <a href="{% url 'modules:module_detail' module.pk %}" class="btn btn-info">Просмотреть модуль</a>
                        {% if request.user == module.owner or request.user.is_superuser %}
                        <a href="{% url 'modules:module_update' module.pk %}" class="btn btn-secondary">Редактировать</a>
                        <a href="{% url 'modules:module_delete' module.pk %}" class="btn btn-danger">Удалить</a>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <li>Нет доступных модулей.</li>
                {% endfor %}
            </ul>
            {% if request.user.is_authenticated %}
            <a href="{% url 'modules:module_create' %}" class="btn btn-success">Создать новый модуль</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Все Уроки</h1>
            <ul class="list-unstyled">
                {% for lesson in lessons %}
                <li class="d-flex justify-content-between align-items-center">
                    <div>
                        <strong>{{ lesson.title }}</strong>
                        <p>Модуль: {{ lesson.module.title }}</p>
                    </div>
                    <div class="btn-group">
                        <a href="{% url 'modules:lesson_detail' lesson.pk %}" class="btn btn-primary">Подробнее</a>
                        {% if request.user == lesson.owner or request.user.is_superuser %}
                        <a href="{% url 'modules:lesson_update' lesson.pk %}" class="btn btn-secondary">Редактировать</a>
                        <a href="{% url 'modules:lesson_delete' lesson.pk %}" class="btn btn-danger">Удалить</a>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <li>Нет доступных уроков.</li>
                {% endfor %}
            </ul>
            {% if request.user.is_authenticated %}
            <a href="{% url 'modules:lesson_create' %}" class="btn btn-success">Создать новый урок</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}