config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.authtoken.views import obtain_auth_token

from modules.views import IndexView

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Educational Modules",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(template_name='modules/index.html'), name='index'),
    path('modules/', include('modules.urls', namespace='modules')),
    path('users/', include('users.urls', namespace='users')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from users.views import UserRegisterView, UserListView, UserLoginView, UserProfileView, UserProfileUpdateView, \
    UserDeleteView, UserPasswordResetConfirmView, UserPasswordResetView, confirm_registration, UserRegisterAPIView

from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'users'

urlpatterns = [
    path('api/register/', UserRegisterAPIView.as_view(), name='api_register'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='profile_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'), # сброс пароля пользователя
    path('password_reset_confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'), # подтверждение сброса пароля пользователя
    path('confirm/<str:token>/', confirm_registration, name='confirmation_link'), # путь ссылки на подтверждение регистрации, которая отправляется пользователю по email
    path('confirm-registration/<uuid:token>/', confirm_registration, name='confirm_registration'), # путь запроса, когда пользователь переходит по ссылке для подтверждения регистрации

# token
    path(
        "users/login/",
        TokenObtainPairView.as_view(permission_classes=(AllowAny,)),
        name="login",
    ),
    path(
        "users/token/refresh/",
        TokenRefreshView.as_view(permission_classes=(AllowAny,)),
        name="token_refresh",
    ),

]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _

NULLABLE = {
    'null': True,
    'blank': True,
}
class CustomUserManager(BaseUserManager):
    """Менеджер для создания пользователей и суперпользователей."""
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """Модель пользователя."""
    email = models.EmailField(unique=True, verbose_name='Почта')
    first_name = models.CharField(max_length=150, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Активирован')
    telegram = models.CharField(max_length=50, verbose_name='Telegram', **NULLABLE)
    token = models.CharField(max_length=50, verbose_name='Токен', **NULLABLE)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserChangeForm, PasswordResetForm, SetPasswordForm
from django import forms
from users.models import User
from django.utils.translation import gettext_lazy as _


class UserRegisterForm(forms.ModelForm):
    """Форма для регистрации нового пользователя"""
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')  # 'username' убрали

    def clean_password2(self):
        """Проверяет, что пароли совпадают"""
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают.")
        return password2

    def save(self, commit=True):
        """Сохраняет нового пользователя с хешированным паролем"""
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])  # Хешируем пароль
        if commit:
            user.save()
        return user

class UserProfileForm(UserChangeForm):
    """Форма для редактирования профиля пользователя"""
    class Meta:
        model = User  # Указываем модель вашей пользовательской модели
        fields = ('email', 'first_name', 'last_name', 'telegram', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class CustomSetPasswordForm(SetPasswordForm):
    """Форма для смены пароля"""
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(user, *args, **kwargs)

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data["new_password1"])
        if commit:
            self.user.save()
        return self.user


class CustomPasswordResetForm(PasswordResetForm):
    """Форма для сброса пароля"""
    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("Указанный адрес электронной почты не существует."), code='nonexistent')
        return email

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.urls import reverse
from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm, CustomSetPasswordForm
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from users.models import User
import uuid
from django.contrib import messages
from rest_framework import generics, status
from rest_framework.response import Response
from users.serializers import UserRegisterSerializer


class UserRegisterAPIView(generics.CreateAPIView):
    """API для регистрации нового пользователя"""
    serializer_class = UserRegisterSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()

        # Генерация ссылки для подтверждения
        confirmation_link = request.build_absolute_uri(reverse('users:confirm_registration', args=[user.token]))

        # Отправка письма
        subject = 'Подтверждение регистрации'
        html_message = render_to_string('users/registration_email.html', {
            'user': user,  # Теперь user должен содержать first_name
            'confirmation_link': confirmation_link
        })
        plain_message = strip_tags(html_message)
        send_mail(subject, plain_message, EMAIL_HOST_USER, [user.email], html_message=html_message)

        return Response({'message': 'Проверьте вашу почту для подтверждения регистрации!'}, status=status.HTTP_201_CREATED)
class UserRegisterView(CreateView):
    """Регистрация нового пользователя"""
    form_class = UserRegisterForm
    template_name = 'users/user_register.html'

    def form_valid(self, form):
        """Сохранение пользователя и отправка письма для подтверждения регистрации"""
        user = form.save(commit=False)
        user.is_active = False
        user.token = self.generate_token()
        user.save()

        # Генерация ссылки для подтверждения
        confirmation_link = self.request.build_absolute_uri(reverse('users:confirm_registration', args=[user.token]))

        # Отправка письма
        subject = 'Подтверждение регистрации'
        html_message = render_to_string('users/registration_email.html', {
            'user': user,
            'confirmation_link': confirmation_link
        })
        plain_message = strip_tags(html_message)
        from_email = EMAIL_HOST_USER
        to_email = user.email
        send_mail(subject, plain_message, from_email, [to_email], html_message=html_message)

        # Показать сообщение о проверке почты
        messages.success(self.request, 'Проверьте вашу почту для подтверждения регистрации!')

        # Перенаправляем на главную страницу
        return redirect(self.get_success_url())

    def get_success_url(self):
        """Возвращает URL-адрес для перенаправления после успешной регистрации"""
        return reverse_lazy('index')

    def generate_token(self):
        """Генерирует уникальный токен для подтверждения регистрации"""
        return str(uuid.uuid4())


class UserListView(ListView):
    """View для отображения списка пользователей"""
    model = User
    template_name = 'users/user_list.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        """Добавляет в контекст URL-адрес для просмотра профиля пользователя"""
        context = super().get_context_data(**kwargs)
        context['user_profile_url'] = reverse_lazy('users:user_profile')
        return context

class UserProfileView(LoginRequiredMixin, UpdateView):
    """View для отображения профиля пользователя"""

    form_class = UserProfileForm
    template_name = 'users/user_profile.html'
    success_url = reverse_lazy('users:user_profile')


    def get_object(self):
        """Возвращает текущего аутентифицированного пользователя"""
        return self.request.user


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    """View для обновления профиля пользователя"""
    form_class = UserProfileForm
    template_name = 'users/profile_update.html'
    success_url = reverse_lazy('users:user_profile')

    def get_object(self, queryset=None):
        """Возвращает текущего аутентифицированного пользователя"""
        return self.request.user


class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """View для удаления профиля пользователя"""
    model = User
    template_name = 'users/user_confirm_delete.html'
    success_url = reverse_lazy('index')

    def test_func(self):
        """Проверяет, что текущий пользователь является владельцем профиля"""
        obj = self.get_object()
        return obj == self.request.user

class UserPasswordResetView(SuccessMessageMixin, PasswordResetView):
    """View для сброса пароля пользователя"""
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject.txt'
    success_message = "Ссылка для сброса пароля была отправлена на вашу почту."

    def get_success_url(self):
        """Перенаправляет на страницу входа после успешного сброса пароля"""
        return reverse_lazy('users:login')


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """View для подтверждения сброса пароля"""
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:login')
    form_class = CustomSetPasswordForm
    success_message = "Ваш пароль успешно обновлен."

# Вход пользователя
class UserLoginView(LoginView):
    template_name = 'users/user_login.html'
    redirect_authenticated_user = True

def confirm_registration(request, token):
    try:
        user = User.objects.get(token=token)
        if user.is_active:
            messages.warning(request, "Регистрация уже подтверждена.")
            return redirect('users:login')

        # Если пользователь не активен, активируем его
        user.is_active = True
        user.token = None
        user.save()
        messages.success(request, "Ваш аккаунт успешно подтвержден! Теперь вы можете войти на сайт.")

        # Перенаправляем пользователя на его профиль после подтверждения регистрации
        return redirect('users:user_profile')

    except User.DoesNotExist:
        messages.error(request, "Неверный токен подтверждения.")
        return redirect('users:login')

users/templates/users/profile_update.html
{% extends 'modules/base.html' %}

{% block content %}

<h1>Обновление профиля</h1>
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
</form>
<a href="{% url 'users:user_profile' %}" class="btn btn-secondary">Назад к профилю</a>
{% endblock %}

users/templates/users/registration_email.html
{% extends 'modules/base.html' %}

{% block content %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение регистрации</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }
        .container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            color: #ffffff;
            background-color: #28a745;
            text-decoration: none;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Привет, {{ user.first_name }}!</h1>
        <p>Спасибо за регистрацию на нашем сайте. Пожалуйста, подтвердите вашу регистрацию, пройдя по следующей ссылке:</p>
        <p>
            <a href="{{ confirmation_link }}" class="button">Подтвердить регистрацию</a>
        </p>
        <p>Если у вас есть вопросы, не стесняйтесь обращаться к нам.</p>
        <p>С уважением,<br>Команда поддержки U-Kids 8 (3472) 777-77-77 </p>
    </div>
</body>
</html>

{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends "modules/base.html" %}
{% block title %}Удалить пользователя{% endblock %}
{% block content %}
<h2>Вы уверены, что хотите удалить пользователя "{{ object.first_name }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'index' %}" class="btn btn-secondary">Назад</a>
</form>
{% endblock %}

users/templates/users/user_list.html
{% extends "modules/base.html" %}
{% block title %}Список пользователей{% endblock %}
{% block content %}
<h2>Список пользователей</h2>
<table class="table">
    <thead>
        <tr>
            <th>Имя пользователя</th>
            <th>Email</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>
                <a href="{% url 'users:user_profile' %}">{{ user.first_name }}</a>
            </td>
            <td>{{ user.email }}</td>
            <td>
                <a href="{% url 'users:user_profile' %}" class="btn btn-info">Просмотр</a>
                {% if user == request.user %}
                <a href="{% url 'users:profile_update' %}" class="btn btn-warning">Изменить</a>
                {% endif %}
                {% if user != request.user and request.user.is_superuser %}
                <a href="{% url 'users:user_delete' user.pk %}" class="btn btn-danger">Удалить</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if request.user.is_superuser %}
<a href="{% url 'users:register' %}" class="btn btn-success">Создать нового пользователя</a>
{% endif %}
{% endblock %}

users/templates/users/user_login.html
{% extends "modules/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Войти</button>
</form>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'base.html' %}

{% block title %}Password Reset{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <h1 class="text-center mb-4">Password Reset</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Reset Password</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'modules/base.html' %}

{% block content %}
<h1>Профиль пользователя</h1>

<div class="profile-details">
    <h2>Личные данные</h2>
    <p><strong>Имя:</strong> {{ user.first_name }}</p>
    <p><strong>Имя:</strong> {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Telegram:</strong> {{ user.telegram }}</p>
</div>

<div class="profile-actions">
    <h2>Действия</h2>
    <a href="{% url 'users:profile_update' %}" class="btn">Редактировать профиль</a>  <!-- Ссылка на редактирование профиля -->
</div>

{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}

{% endblock %}

users/templates/users/user_register.html
{% extends 'modules/base.html' %}
{% load static %}

{% block content %}
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>
{% endblock %}